Add vllm results into verification report
Signed-off-by: Ben Browning <bbrownin@redhat.com>

diff --git a/.github/workflows/openai-api-verification.yaml b/.github/workflows/openai-api-verification.yaml
--- a/.github/workflows/openai-api-verification.yaml
+++ b/.github/workflows/openai-api-verification.yaml
@@ -72,12 +72,37 @@ jobs:
       - name: Run verification tests
         run: |
           source .venv/bin/activate
+          mkdir -p tests/verifications/test_results
+
+          for provider in together fireworks groq openai together-llama-stack fireworks-llama-stack groq-llama-stack openai-llama-stack; do
+            python -m pytest -s -v tests/verifications/openai_api/test_chat_completion.py --provider="${provider}" --json-report --json-report-file="tests/verifications/test_results/${provider}.json" || echo "some ${provider} verification tests failed"
+          done
+        env:
+          FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
+          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
+          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
+
+      - name: Checkout vllm results
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          repository: "instructlab/lls-openai-client"
+          ref: "main"
+          path: vllm_results
+
+      - name: Generate report
+        run: |
+          source .venv/bin/activate
+
+          cp vllm_results/openai-api-verification/latest/*.json tests/verifications/test_results/
+
           python tests/verifications/generate_report.py \
-            --run-tests \
-            --providers together \
+            --providers vllm \
+                        together \
                         fireworks \
                         groq \
                         openai \
+                        vllm-llama-stack \
                         together-llama-stack \
                         fireworks-llama-stack \
                         groq-llama-stack \
@@ -87,11 +112,6 @@ jobs:
           cat verification_report.md | grep "Generated on"
           # Add the verification report to the step summary
           cat verification_report.md >> $GITHUB_STEP_SUMMARY
-        env:
-          FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
-          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
-          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
 
       - name: Upload report artifact
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
